// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjAJQx79TYEZ9xbx5jgBiZ4nvWdFxD8T8',
    appId: '1:392329008088:web:6fd958926c04b7b83fd8ad',
    messagingSenderId: '392329008088',
    projectId: 'trippy-prod-4524f',
    authDomain: 'trippy-prod-4524f.firebaseapp.com',
    storageBucket: 'trippy-prod-4524f.firebasestorage.app',
    measurementId: 'G-0DZ0NKGTKH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLl1yvBHCFzHCN4u6hk_0ds0Q6of5ZmY',
    appId: '1:392329008088:android:bea8a7ff87c1c9f13fd8ad',
    messagingSenderId: '392329008088',
    projectId: 'trippy-prod-4524f',
    storageBucket: 'trippy-prod-4524f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8xsSQlRVgIYerijYlVCLtkVzf5hIktGM',
    appId: '1:392329008088:ios:9a4d2e4a40b6525b3fd8ad',
    messagingSenderId: '392329008088',
    projectId: 'trippy-prod-4524f',
    storageBucket: 'trippy-prod-4524f.firebasestorage.app',
    iosClientId: '392329008088-p4bmvvg30n8s1o4o0vsgrcns661iqctq.apps.googleusercontent.com',
    iosBundleId: 'com.roljs.trippy',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8xsSQlRVgIYerijYlVCLtkVzf5hIktGM',
    appId: '1:392329008088:ios:3a6ae2e3d70a47833fd8ad',
    messagingSenderId: '392329008088',
    projectId: 'trippy-prod-4524f',
    storageBucket: 'trippy-prod-4524f.firebasestorage.app',
    iosClientId: '392329008088-omh2drr3unok6gqc1c8jc1frqb46g1f9.apps.googleusercontent.com',
    iosBundleId: 'com.trippy.trippy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjAJQx79TYEZ9xbx5jgBiZ4nvWdFxD8T8',
    appId: '1:392329008088:web:1fb9fed5552fb6d93fd8ad',
    messagingSenderId: '392329008088',
    projectId: 'trippy-prod-4524f',
    authDomain: 'trippy-prod-4524f.firebaseapp.com',
    storageBucket: 'trippy-prod-4524f.firebasestorage.app',
    measurementId: 'G-KFRF0WNK6K',
  );
}
